# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/our_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# XDC: C:/Users/Darshana/Documents/GitHub/JitFilt/ESP1/FPGA1/FPGA1/FPGA1.gen/sources_1/bd/design_1/design_1_ooc.xdc
